MySQL:
  Enable: true
  Host: 'localhost'
  Port: 3306
  Database: 'diversemc'
  Username: 'root'
  Password: ''
BuildMode: true
WorldFFA: 'world'
AutoRespawn: true
FallDamage: false
Scoreboard: true
SpawnRegion: 'spawn'
Spawn: